# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una facultad con este nombre'}, max_length=50, unique=True, verbose_name='Facultad'),
        ),
    ]
