# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 06:45
from __future__ import unicode_literals

import apps.administrador.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_auto_20170219_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='ruta',
            field=models.ImageField(help_text='Esta lista de opcines le permite asignar una carrera de enfoque a la imagen.', upload_to=apps.administrador.models.imagen),
        ),
    ]
