# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 02:31
from __future__ import unicode_literals

import apps.administrador.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0003_auto_20170220_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(upload_to=apps.administrador.models.imagen)),
            ],
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='ruta',
        ),
        migrations.AlterField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(blank=True, help_text='Este campo hace referencia al contendio.', max_length=50),
        ),
        migrations.AddField(
            model_name='foto',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Imagen'),
        ),
    ]
