# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-08 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_auto_20170307_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='titulo',
            field=models.CharField(default='Prueba', help_text='Este campo hace referencia al contendio.', max_length=50),
            preserve_default=False,
        ),
    ]
